version: "3.9"

networks:
  elastic:
    driver: bridge

services:
  torch3d:
    image: 3llobo/torch3dfinal:latest
    container_name: torch3d
    restart: unless-stopped
    ports:
      - 9881:9881
      - 8888:8888
    volumes:
      - ./:/app:rw
    # GPU support
    entrypoint: [ "tail", "-f", "/dev/null" ]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
